#!/bin/sh
#
# $RCSfile$
#

if [ ! -d "adm" -a ! -f "VERSION" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

# this has become exceedingly simple.
cat VERSION

