#!/bin/sh
#
# $Id: get_version 348 2001-11-06 06:50:46Z blais $
#

if [ ! -d "tools" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

grep XX_VERSION src/version.h | egrep -v debug | sed -e 's/[^"]*"//;s/".*//'

