#!/bin/sh

libtoolize -f -c
if [ "$PLAT" != "i686-pc-linux-gnu" ]; then
	automake --foreign -i
else
	automake --foreign
fi
aclocal
autoconf
if [ "$SITE" = "discreet" ]; then
	/usr/bin/perl ./automoc
else
	perl ./automoc
fi

rm -f config.cache
if [ "$PLAT" = "mips-sgi-irix6.5" ]; then
	LD=CC CXX=CC ./configure $* 

elif [ "$PLAT" = "i686-pc-linux-gnu" ]; then
	LD=gcc ./configure $*

else
	./configure $*
fi
