#!/bin/sh

echo "Running aclocal..."
aclocal

echo "Running libtoolize..."
libtoolize -f -c

echo "Running automake..."
if [ "$PLAT" != "i686-pc-linux-gnu" ]; then
	automake --foreign -i
else
	automake --foreign
fi

echo "Running aclocal again..."
aclocal

echo "Running autoconf..."
autoconf

echo "Running automoc..."
if [ "$SITE" = "discreet" ]; then
	 /usr/bin/perl ./automoc
else
	 perl ./automoc
fi

echo "Removing cache..."
rm -f config.cache

echo "Running configure..."
if [ "$PLAT" = "mips-sgi-irix6.5" ]; then
	LD=CC CXX=CC ./configure $* 

elif [ "$PLAT" = "i686-pc-linux-gnu" ]; then
	LD=gcc ./configure $*

else
	./configure $*
fi
