#!/bin/sh
#
# $Id: release_mips_tardist 352 2001-11-06 20:00:01Z blais $
#

if [ ! -d "tools" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

VERSION=`tools/get_version`

SBASE=$HOME/xxdiff
COMPONENTS="xxdiff xxdiff.idb xxdiff.sw xxdiff.man"
DEST=$PWD/../xxdiff-$VERSION.mips.tardist

# Generate distribution.
gendist -sbase $SBASE -idb $SBASE/tools/xxdiff-sgi.idb \
 -spec $SBASE/tools/xxdiff-sgi.spec -dist /tmp -all

( cd /tmp  ; tar cvf $DEST $COMPONENTS ; rm $COMPONENTS )

