#!/bin/sh
#
# $RCSfile$
#

if [ ! -d "tools" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

# Note: this script assume that release_bin has already been called.

echo "== Getting version number"
VERSION=`tools/get_version`
echo "==   Version is " $VERSION

echo "== Getting and creating top dir"
BUILDROOT=`rpm --showrc | egrep "[^{]_topdir" | cut --fields=2 | sed -e 'sX%{_usrsrc}X/usr/srcX'`
mkdir -p $BUILDROOT/{SPECS,SOURCES,BUILD,SRPMS,RPMS}

# echo "== Creating spec file"
# cp tools/xxdiff-rpm.spec $BUILDROOT/SPECS/xxdiff-$VERSION.spec

echo "== Copying pristine build to $BUILDROOT/SOURCES"
PRISTINE=../xxdiff-$VERSION.tar.gz
if [ ! -f "$PRISTINE" ]; then
     echo "Cannot find pristine sources in $PRISTINE"
fi
cp $PRISTINE $BUILDROOT/SOURCES

echo "== Building source and binary packages"
# Note: we use nodeps here because tmake package is not quite common yet under 
# rh-7.1.

# use -bs to build source only

rpm -ba --nodeps --clean --rmsource tools/xxdiff-rpm.spec

#rpm -bs --nodeps tools/xxdiff-rpm.spec
#rpm -bs --nodeps --rmsource --rmspec $BUILDROOT/SPECS/xxdiff-$VERSION.spec
#rpm -bs --nodeps --rmsource --rmspec $BUILDROOT/SPECS/xxdiff-$VERSION.spec
#rpm -ts --nodeps --clean --rmsource --rmspec $PRISTINE

DEST=$HOME
echo "== Copying source and binary packages to $DEST"
cp $BUILDROOT/RPMS/i386/xxdiff-$VERSION*.i386.rpm $DEST
cp $BUILDROOT/SRPMS/xxdiff-$VERSION*.src.rpm $DEST

echo "== Signing package files in $DEST"
rpm --addsign $DEST/xxdiff-$VERSION*.rpm

echo "== Done."
