#!/bin/sh
#
# $Id: release_src 348 2001-11-06 06:50:46Z blais $
#

if [ ! -d "tools" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

# Package for source release.
echo "Getting version"
VERSION=`tools/get_version`
UVERSION=`echo $VERSION | sed -e 's/\./_/g'`
echo "Version $VERSION, Release tag $UVERSION"

echo "Creating temporary space to extract source"
TMP=xxdiff-tmp

cd .. && mkdir $TMP && cd $TMP

echo "Exporting source from CVS"
CVS_RSH=ssh
cvs -z3 -d:ext:bor.iro.umontreal.ca:/u/blais/cvsroot \
   export -d xxdiff-$VERSION -r xxdiff_$UVERSION xxdiff

echo "Compressing source into archive"
tar zcvf xxdiff-${VERSION}.tar.gz xxdiff-${VERSION}

echo "Cleaning up"
cd .. && rm -rf $TMP
