#!/bin/sh
#
# $Id: release_i386_rpm 348 2001-11-06 06:50:46Z blais $
#

if [ ! -d "tools" ]; then
     echo "You must be running this script from the topdir directory."
     exit 1;
fi

# Note: this script assume that release_bin has already been called.

echo "Getting version number"
VERSION=`tools/get_version`
echo "   Version is " $VERSION

echo "Creating spec file"
cp tools/xxdiff-rpm.spec > /usr/src/redhat/SPECS/xxdiff-$VERSION.spec

echo "Copying pristine build"
PRISTINE=../xxdiff-$VERSION.tar.gz
if [ ! -f "$PRISTINE" ]; then
     echo "You must run release_src before running this script."
fi
cp $PRISTINE /usr/src/redhat/SOURCES

echo "Building binary package"
rpm -ba /usr/src/redhat/SPECS/xxdiff-$VERSION.spec

echo "Copy binary package home"
cp /usr/src/redhat/RPMS/i386/xxdiff-$VERSION*.i386.rpm /home/blais
chmod 777 /home/blais/xxdiff-$VERSION*.i386.rpm

cp /usr/src/redhat/RPMS/i386/xxdiff-$VERSION*.src.rpm /home/blais
chmod 777 /home/blais/xxdiff-$VERSION*.src.rpm

echo "Done."
