.\" $$RCSfile$
.\"
.\" Copyright (C) 1999-2002 Martin Blais <blais@furius.ca>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.na
.TH XXDIFF 1
.SH NAME
xxdiff \- a graphical file comparator and merge tool
.SH SYNOPSIS
xxdiff [OPTIONS] <path> <path> [<path>]
.SH OVERVIEW
.LP
.I xxdiff
is a graphical file and directories comparison and merge tool. It can be used
for viewing the differences between two or three files, or two directories, and
can be used to produce a merged version. The texts of the two or three files are
presented side by side with their differences highlighted with colors for easy
identification.
.LP 
The paths supplied on the command line identify the files to be compared.  The
paths may be one of three things:  a regular file, a directory or a '-', in
which case the input for that path will be read from standard input.  If the
paths are all directories, a directory diff will be performed.  If at least one
path is a file or a '-', a file diff will be performed.  If there are directory
names along with file names, the basename of the file name will be appended to
the directory names to find the other files to compare with.  If there are
multiple file names specified and some directories names as well, xxdiff bails
out, since it doesn't know which basename to use for the missing one.
.LP 
Please consult xxdiff \-\-help for more documentation.
.SH OPTIONS
.LP
.TP 8
.B \-\-help         
Show help about options.
.TP 8
.B \-\-help\-qt
Show Qt specific options.
.TP 8
.B \-\-help\-all
Show all options.
.TP 8
.B \-\-help\-html
Output documentation in HTML.
.TP 8
.B \-\-version, \-v  
Show version information and compilation options it was built with.
.SH DIAGNOSTICS
Returns the exit status generated by the 
.I diff
command.  This is usually 0 for no differences, 1 for some differences
and 2 for errors.
.SH SEE ALSO
.BR diff (1),
.BR xxdiff\-encrypted.html,
.BR xxdiff\-match.html,
.BR xxdiff\-cvs\-diff.html,
.BR xxdiff\-find\-grep\-sed.html,
.BR xxdiff\-match.html
.SH COPYRIGHT
Copyright (C) 1999, 2000, 2001, 2003  Martin Blais
.LP
See the GNU General Public License
for a full statement of rights and permissions.
.SH AUTHOR
Martin Blais <blais@furius.ca>
.LP
Debian Linux package is maintained by Tomas Pospisek <tpo_deb@sourcepole.ch>.
